### PR TITLE
5GMS - Media Stream Handler: QoE metrics collection feature

### PR DESCRIPTION
**Pull request by dsilhavy**
* Add logic to process metrics reporting scheme capability requests from the Media Session Handler
* Add logic to process metrics reporting messages requests from the Media Session Handler
* Add additional methods to the `ExoPlayerAdapter` to reset metrics in the `ExoPlayerListener` and query information such as the manifest URL
* Add support for deriving `HTTPList`, `RepresentationSwitchList`, `MPDInformation`, and `BufferLevel` metrics according to 26.247

### CODE REVIEW

**Comment by rjb1000** [comment]
(Minor comment to reframe this change slightly: the client metrics reporting configuration supplied to the Media Session Handler at reference point M5 is not an indication of the 5GMS AF's capabilities. Rather, it is a specification provided by the 5GMS AF of the metrics that the 5GMS Client is required to supply.)

**Comment by rjb1000** [comment]
Another small comment on the naming of methods/functions and variables in the code: each metrics reporting scheme defines a (plural) set of metrics, so `metricScheme` should be `metricsScheme` throughout.

**Comment by dsilhavy** [comment]
Thanks @rjb1000 for the review and the comments. I renamed the variables accordingly. 

One question regarding your first comment: You were referring to the description I made in the pull request, right? I think my description was not clear, what I implemented is a message handler to respond to the initial request by the Media Session Handler for metric collection capabilities:

_The Media Session Handler queries the Media Player on its capability to perform metrics collection (measurement and logging function) in accordance with both schemes 1 and 2 as defined by its metrics configuration._

**Comment by rjb1000** [comment]
Yes, it was just the description of the PR that was confusing.

**Pull request closed without merging**
